/*
 * CrossID Public API
 *
 * CrossID API Reference 
 *
 * API version: 1.0.0
 * Contact: developer@crossid.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// VerificationFlowMethods struct for VerificationFlowMethods
type VerificationFlowMethods struct {
	Code *VerificationFlowMethod `json:"code,omitempty"`
}

// NewVerificationFlowMethods instantiates a new VerificationFlowMethods object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationFlowMethods() *VerificationFlowMethods {
	this := VerificationFlowMethods{}
	return &this
}

// NewVerificationFlowMethodsWithDefaults instantiates a new VerificationFlowMethods object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationFlowMethodsWithDefaults() *VerificationFlowMethods {
	this := VerificationFlowMethods{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *VerificationFlowMethods) GetCode() VerificationFlowMethod {
	if o == nil || o.Code == nil {
		var ret VerificationFlowMethod
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerificationFlowMethods) GetCodeOk() (*VerificationFlowMethod, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *VerificationFlowMethods) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given VerificationFlowMethod and assigns it to the Code field.
func (o *VerificationFlowMethods) SetCode(v VerificationFlowMethod) {
	o.Code = &v
}

func (o VerificationFlowMethods) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableVerificationFlowMethods struct {
	value *VerificationFlowMethods
	isSet bool
}

func (v NullableVerificationFlowMethods) Get() *VerificationFlowMethods {
	return v.value
}

func (v *NullableVerificationFlowMethods) Set(val *VerificationFlowMethods) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationFlowMethods) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationFlowMethods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationFlowMethods(val *VerificationFlowMethods) *NullableVerificationFlowMethods {
	return &NullableVerificationFlowMethods{value: val, isSet: true}
}

func (v NullableVerificationFlowMethods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationFlowMethods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


