/*
 * CrossID Public API
 *
 * CrossID API Reference 
 *
 * API version: 1.0.0
 * Contact: developer@crossid.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// InsightList struct for InsightList
type InsightList struct {
	Items []Insight
}

// NewInsightList instantiates a new InsightList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsightList() *InsightList {
	this := InsightList{}
	return &this
}

// NewInsightListWithDefaults instantiates a new InsightList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsightListWithDefaults() *InsightList {
	this := InsightList{}
	return &this
}

func (o InsightList) MarshalJSON() ([]byte, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	return json.Marshal(toSerialize)
}

func (o *InsightList) UnmarshalJSON(bytes []byte) (err error) {
	return json.Unmarshal(bytes, &o.Items)
}

type NullableInsightList struct {
	value *InsightList
	isSet bool
}

func (v NullableInsightList) Get() *InsightList {
	return v.value
}

func (v *NullableInsightList) Set(val *InsightList) {
	v.value = val
	v.isSet = true
}

func (v NullableInsightList) IsSet() bool {
	return v.isSet
}

func (v *NullableInsightList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsightList(val *InsightList) *NullableInsightList {
	return &NullableInsightList{value: val, isSet: true}
}

func (v NullableInsightList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsightList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


