/*
 * CrossID Public API
 *
 * CrossID API Reference 
 *
 * API version: 1.0.0
 * Contact: developer@crossid.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// RegistrationFlowMethods struct for RegistrationFlowMethods
type RegistrationFlowMethods struct {
	Password *RegistrationFlowMethod `json:"password,omitempty"`
	Spnego *RegistrationFlowMethod `json:"spnego,omitempty"`
	Webauthn *RegistrationFlowMethod `json:"webauthn,omitempty"`
}

// NewRegistrationFlowMethods instantiates a new RegistrationFlowMethods object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationFlowMethods() *RegistrationFlowMethods {
	this := RegistrationFlowMethods{}
	return &this
}

// NewRegistrationFlowMethodsWithDefaults instantiates a new RegistrationFlowMethods object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationFlowMethodsWithDefaults() *RegistrationFlowMethods {
	this := RegistrationFlowMethods{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *RegistrationFlowMethods) GetPassword() RegistrationFlowMethod {
	if o == nil || o.Password == nil {
		var ret RegistrationFlowMethod
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationFlowMethods) GetPasswordOk() (*RegistrationFlowMethod, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *RegistrationFlowMethods) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given RegistrationFlowMethod and assigns it to the Password field.
func (o *RegistrationFlowMethods) SetPassword(v RegistrationFlowMethod) {
	o.Password = &v
}

// GetSpnego returns the Spnego field value if set, zero value otherwise.
func (o *RegistrationFlowMethods) GetSpnego() RegistrationFlowMethod {
	if o == nil || o.Spnego == nil {
		var ret RegistrationFlowMethod
		return ret
	}
	return *o.Spnego
}

// GetSpnegoOk returns a tuple with the Spnego field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationFlowMethods) GetSpnegoOk() (*RegistrationFlowMethod, bool) {
	if o == nil || o.Spnego == nil {
		return nil, false
	}
	return o.Spnego, true
}

// HasSpnego returns a boolean if a field has been set.
func (o *RegistrationFlowMethods) HasSpnego() bool {
	if o != nil && o.Spnego != nil {
		return true
	}

	return false
}

// SetSpnego gets a reference to the given RegistrationFlowMethod and assigns it to the Spnego field.
func (o *RegistrationFlowMethods) SetSpnego(v RegistrationFlowMethod) {
	o.Spnego = &v
}

// GetWebauthn returns the Webauthn field value if set, zero value otherwise.
func (o *RegistrationFlowMethods) GetWebauthn() RegistrationFlowMethod {
	if o == nil || o.Webauthn == nil {
		var ret RegistrationFlowMethod
		return ret
	}
	return *o.Webauthn
}

// GetWebauthnOk returns a tuple with the Webauthn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationFlowMethods) GetWebauthnOk() (*RegistrationFlowMethod, bool) {
	if o == nil || o.Webauthn == nil {
		return nil, false
	}
	return o.Webauthn, true
}

// HasWebauthn returns a boolean if a field has been set.
func (o *RegistrationFlowMethods) HasWebauthn() bool {
	if o != nil && o.Webauthn != nil {
		return true
	}

	return false
}

// SetWebauthn gets a reference to the given RegistrationFlowMethod and assigns it to the Webauthn field.
func (o *RegistrationFlowMethods) SetWebauthn(v RegistrationFlowMethod) {
	o.Webauthn = &v
}

func (o RegistrationFlowMethods) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.Spnego != nil {
		toSerialize["spnego"] = o.Spnego
	}
	if o.Webauthn != nil {
		toSerialize["webauthn"] = o.Webauthn
	}
	return json.Marshal(toSerialize)
}

type NullableRegistrationFlowMethods struct {
	value *RegistrationFlowMethods
	isSet bool
}

func (v NullableRegistrationFlowMethods) Get() *RegistrationFlowMethods {
	return v.value
}

func (v *NullableRegistrationFlowMethods) Set(val *RegistrationFlowMethods) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationFlowMethods) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationFlowMethods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationFlowMethods(val *RegistrationFlowMethods) *NullableRegistrationFlowMethods {
	return &NullableRegistrationFlowMethods{value: val, isSet: true}
}

func (v NullableRegistrationFlowMethods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationFlowMethods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


