/*
 * CrossID Public API
 *
 * CrossID API Reference 
 *
 * API version: 1.0.0
 * Contact: developer@crossid.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// EntitlementRequest struct for EntitlementRequest
type EntitlementRequest struct {
	Operations *[]EntitlementRequestOperations `json:"operations,omitempty"`
}

// NewEntitlementRequest instantiates a new EntitlementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementRequest() *EntitlementRequest {
	this := EntitlementRequest{}
	return &this
}

// NewEntitlementRequestWithDefaults instantiates a new EntitlementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementRequestWithDefaults() *EntitlementRequest {
	this := EntitlementRequest{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *EntitlementRequest) GetOperations() []EntitlementRequestOperations {
	if o == nil || o.Operations == nil {
		var ret []EntitlementRequestOperations
		return ret
	}
	return *o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitlementRequest) GetOperationsOk() (*[]EntitlementRequestOperations, bool) {
	if o == nil || o.Operations == nil {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *EntitlementRequest) HasOperations() bool {
	if o != nil && o.Operations != nil {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []EntitlementRequestOperations and assigns it to the Operations field.
func (o *EntitlementRequest) SetOperations(v []EntitlementRequestOperations) {
	o.Operations = &v
}

func (o EntitlementRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Operations != nil {
		toSerialize["operations"] = o.Operations
	}
	return json.Marshal(toSerialize)
}

type NullableEntitlementRequest struct {
	value *EntitlementRequest
	isSet bool
}

func (v NullableEntitlementRequest) Get() *EntitlementRequest {
	return v.value
}

func (v *NullableEntitlementRequest) Set(val *EntitlementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementRequest(val *EntitlementRequest) *NullableEntitlementRequest {
	return &NullableEntitlementRequest{value: val, isSet: true}
}

func (v NullableEntitlementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


