// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crossid/crossid-client-go/models"
)

// ListAppsReader is a Reader for the ListApps structure.
type ListAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAppsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAppsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListAppsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAppsOK creates a ListAppsOK with default headers values
func NewListAppsOK() *ListAppsOK {
	return &ListAppsOK{}
}

/*ListAppsOK handles this case with default header values.

list of apps.
*/
type ListAppsOK struct {
	Payload *ListAppsOKBody
}

func (o *ListAppsOK) Error() string {
	return fmt.Sprintf("[GET /apps][%d] listAppsOK  %+v", 200, o.Payload)
}

func (o *ListAppsOK) GetPayload() *ListAppsOKBody {
	return o.Payload
}

func (o *ListAppsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListAppsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAppsBadRequest creates a ListAppsBadRequest with default headers values
func NewListAppsBadRequest() *ListAppsBadRequest {
	return &ListAppsBadRequest{}
}

/*ListAppsBadRequest handles this case with default header values.

genericError
*/
type ListAppsBadRequest struct {
	Payload models.GenericError
}

func (o *ListAppsBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps][%d] listAppsBadRequest  %+v", 400, o.Payload)
}

func (o *ListAppsBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *ListAppsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAppsInternalServerError creates a ListAppsInternalServerError with default headers values
func NewListAppsInternalServerError() *ListAppsInternalServerError {
	return &ListAppsInternalServerError{}
}

/*ListAppsInternalServerError handles this case with default header values.

genericError
*/
type ListAppsInternalServerError struct {
	Payload models.GenericError
}

func (o *ListAppsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /apps][%d] listAppsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAppsInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *ListAppsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListAppsOKBody list apps o k body
swagger:model ListAppsOKBody
*/
type ListAppsOKBody struct {

	// The number of resources returned in a list response page.
	ItemsPerPage int64 `json:"itemsPerPage,omitempty"`

	// A list of applications that match the given options
	// This MAY be a subset of the full set of resources if pagination is requested.
	Resources []*models.AppManifest `json:"Resources"`

	// The 1-based index of the first result in the current set of list results.
	// REQUIRED when partial results are returned due to pagination
	StartIndex int64 `json:"startIndex,omitempty"`

	// The total number of results returned by the list or query operation
	// The value may be larger than the number of resources returned
	// such as when returning a single page of results where multiple pages are available.
	// required when partial results are returned due to pagination.
	TotalResults int64 `json:"totalResults,omitempty"`
}

// Validate validates this list apps o k body
func (o *ListAppsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListAppsOKBody) validateResources(formats strfmt.Registry) error {

	if swag.IsZero(o.Resources) { // not required
		return nil
	}

	for i := 0; i < len(o.Resources); i++ {
		if swag.IsZero(o.Resources[i]) { // not required
			continue
		}

		if o.Resources[i] != nil {
			if err := o.Resources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listAppsOK" + "." + "Resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListAppsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListAppsOKBody) UnmarshalBinary(b []byte) error {
	var res ListAppsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
