// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListAppsParams creates a new ListAppsParams object
// with the default values initialized.
func NewListAppsParams() *ListAppsParams {
	var (
		countDefault = int64(10)
	)
	return &ListAppsParams{
		Count: &countDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListAppsParamsWithTimeout creates a new ListAppsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAppsParamsWithTimeout(timeout time.Duration) *ListAppsParams {
	var (
		countDefault = int64(10)
	)
	return &ListAppsParams{
		Count: &countDefault,

		timeout: timeout,
	}
}

// NewListAppsParamsWithContext creates a new ListAppsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAppsParamsWithContext(ctx context.Context) *ListAppsParams {
	var (
		countDefault = int64(10)
	)
	return &ListAppsParams{
		Count: &countDefault,

		Context: ctx,
	}
}

// NewListAppsParamsWithHTTPClient creates a new ListAppsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAppsParamsWithHTTPClient(client *http.Client) *ListAppsParams {
	var (
		countDefault = int64(10)
	)
	return &ListAppsParams{
		Count:      &countDefault,
		HTTPClient: client,
	}
}

/*ListAppsParams contains all the parameters to send to the API endpoint
for the list apps operation typically these are written to a http.Request
*/
type ListAppsParams struct {

	/*Attributes*/
	Attributes []string
	/*Count*/
	Count *int64
	/*Filter*/
	Filter *string
	/*SortBy*/
	SortBy *string
	/*SortOrder*/
	SortOrder *string
	/*StartIndex*/
	StartIndex *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list apps params
func (o *ListAppsParams) WithTimeout(timeout time.Duration) *ListAppsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list apps params
func (o *ListAppsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list apps params
func (o *ListAppsParams) WithContext(ctx context.Context) *ListAppsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list apps params
func (o *ListAppsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list apps params
func (o *ListAppsParams) WithHTTPClient(client *http.Client) *ListAppsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list apps params
func (o *ListAppsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributes adds the attributes to the list apps params
func (o *ListAppsParams) WithAttributes(attributes []string) *ListAppsParams {
	o.SetAttributes(attributes)
	return o
}

// SetAttributes adds the attributes to the list apps params
func (o *ListAppsParams) SetAttributes(attributes []string) {
	o.Attributes = attributes
}

// WithCount adds the count to the list apps params
func (o *ListAppsParams) WithCount(count *int64) *ListAppsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the list apps params
func (o *ListAppsParams) SetCount(count *int64) {
	o.Count = count
}

// WithFilter adds the filter to the list apps params
func (o *ListAppsParams) WithFilter(filter *string) *ListAppsParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the list apps params
func (o *ListAppsParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithSortBy adds the sortBy to the list apps params
func (o *ListAppsParams) WithSortBy(sortBy *string) *ListAppsParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list apps params
func (o *ListAppsParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithSortOrder adds the sortOrder to the list apps params
func (o *ListAppsParams) WithSortOrder(sortOrder *string) *ListAppsParams {
	o.SetSortOrder(sortOrder)
	return o
}

// SetSortOrder adds the sortOrder to the list apps params
func (o *ListAppsParams) SetSortOrder(sortOrder *string) {
	o.SortOrder = sortOrder
}

// WithStartIndex adds the startIndex to the list apps params
func (o *ListAppsParams) WithStartIndex(startIndex *int64) *ListAppsParams {
	o.SetStartIndex(startIndex)
	return o
}

// SetStartIndex adds the startIndex to the list apps params
func (o *ListAppsParams) SetStartIndex(startIndex *int64) {
	o.StartIndex = startIndex
}

// WriteToRequest writes these params to a swagger request
func (o *ListAppsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesAttributes := o.Attributes

	joinedAttributes := swag.JoinByFormat(valuesAttributes, "")
	// query array param attributes
	if err := r.SetQueryParam("attributes", joinedAttributes...); err != nil {
		return err
	}

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string
		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {
			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}

	}

	if o.SortOrder != nil {

		// query param sortOrder
		var qrSortOrder string
		if o.SortOrder != nil {
			qrSortOrder = *o.SortOrder
		}
		qSortOrder := qrSortOrder
		if qSortOrder != "" {
			if err := r.SetQueryParam("sortOrder", qSortOrder); err != nil {
				return err
			}
		}

	}

	if o.StartIndex != nil {

		// query param startIndex
		var qrStartIndex int64
		if o.StartIndex != nil {
			qrStartIndex = *o.StartIndex
		}
		qStartIndex := swag.FormatInt64(qrStartIndex)
		if qStartIndex != "" {
			if err := r.SetQueryParam("startIndex", qStartIndex); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
