/*
 * CrossID Public API
 *
 * CrossID API Reference 
 *
 * API version: 1.0.0
 * Contact: developer@crossid.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// SessionIdentity struct for SessionIdentity
type SessionIdentity struct {
	DisplayName *string `json:"displayName,omitempty"`
}

// NewSessionIdentity instantiates a new SessionIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionIdentity() *SessionIdentity {
	this := SessionIdentity{}
	return &this
}

// NewSessionIdentityWithDefaults instantiates a new SessionIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionIdentityWithDefaults() *SessionIdentity {
	this := SessionIdentity{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *SessionIdentity) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionIdentity) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SessionIdentity) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *SessionIdentity) SetDisplayName(v string) {
	o.DisplayName = &v
}

func (o SessionIdentity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	return json.Marshal(toSerialize)
}

type NullableSessionIdentity struct {
	value *SessionIdentity
	isSet bool
}

func (v NullableSessionIdentity) Get() *SessionIdentity {
	return v.value
}

func (v *NullableSessionIdentity) Set(val *SessionIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionIdentity(val *SessionIdentity) *NullableSessionIdentity {
	return &NullableSessionIdentity{value: val, isSet: true}
}

func (v NullableSessionIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


